services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ipam
      POSTGRES_PASSWORD: ipam
      POSTGRES_DB: ipam
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://ipam:ipam@db:5432/ipam
      JWT_SECRET_KEY: dev-secret
      JWT_REFRESH_SECRET_KEY: dev-refresh
      ACCESS_TOKEN_EXPIRE_MINUTES: "15"
      REFRESH_TOKEN_EXPIRE_DAYS: "7"
      CORS_ORIGINS: https://ipam-tool.vercel.app,https://localhost:5173,http://localhost:5173
      LOG_LEVEL: info
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  dbdata:
