app = "ipam-tool"
primary_region = "sjc"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"
  method = "get"
  path = "/healthz"
  protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
